{{- range $name, $service := .Values.services }}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $service.image }}

spec:
  replicas: {{ $.Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ $service.image }}

  template:
    metadata:
      labels:
        app: {{ $service.image }}

    spec:
      containers:
        - name: {{ $service.image }}

          image: "{{ $service.image }}:{{ $service.tag }}"
          imagePullPolicy: {{ $.Values.imagePullPolicy }}

          ports:
            - containerPort: {{ $service.port }}

          resources:
            {{- toYaml $.Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: {{ $.Values.probes.liveness.path }}
              port: {{ $service.port }}
            initialDelaySeconds: {{ $.Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ $.Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ $.Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ $.Values.probes.liveness.failureThreshold }}

          readinessProbe:
            httpGet:
              path: {{ $.Values.probes.readiness.path }}
              port: {{ $service.port }}
            initialDelaySeconds: {{ $.Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ $.Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ $.Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ $.Values.probes.readiness.failureThreshold }}

---
{{- end }}